version: '3'

services:
  ###> doctrine/doctrine-bundle ###
  database:
    image: 'mysql:latest'
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: debug_db
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3307:3306'
    networks:
      - dev

  phpmyadmin:
    depends_on:
      - database
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_HOST: database
    networks:
      - dev
  php:
    restart: unless-stopped
    image: php:8.2-zts-alpine3.17
    volumes:
      - ./:/var/www/html
    depends_on:
      - database
    environment:
      APP_ENV: dev
      # DATABASE_URL: postgresql://grafikart:grafikart@db:5432/grafikart?serverVersion=12&chartset=utf8

###< doctrine/doctrine-bundle ###
volumes:
  ###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
networks:
  dev: